# Copyright 2017 Hardi Bales-Stutes

---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  require_chef_omnibus: 12

verifier:
  name: inspec

platforms:
  - name: centos-7.3
    driver:
      box: bento/centos-7.3
      network:
      - ["forwarded_port", {guest: 25565, host: 25565}]
suites:
  - name: server
    run_list:
      - recipe[hardi_docker_minecraft::docker]
      - recipe[hardi_docker_minecraft::server]
    verifier:
      inspec_tests:
        - test/smoke/server
    attributes:
      hardi_docker_minecraft:
        server:
          image:
            tag: "latest"
